[2023-03-13T20:19:35.855+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T20:02:10.645643+00:00 [queued]>
[2023-03-13T20:19:35.869+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T20:02:10.645643+00:00 [queued]>
[2023-03-13T20:19:35.869+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:19:35.869+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T20:19:35.870+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:19:35.890+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 20:02:10.645643+00:00
[2023-03-13T20:19:35.893+0000] {standard_task_runner.py:55} INFO - Started process 43547 to run task
[2023-03-13T20:19:35.898+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T20:02:10.645643+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpzh6gnal_']
[2023-03-13T20:19:35.900+0000] {standard_task_runner.py:83} INFO - Job 265: Subtask Chargement_des_données_in_ELK
[2023-03-13T20:19:35.967+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T20:02:10.645643+00:00 [running]> on host dev
[2023-03-13T20:19:36.037+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T20:02:10.645643+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T20:02:10.645643+00:00
[2023-03-13T20:19:36.039+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T20:19:36.040+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bin/logstash -f /home/dev/etc/logstash/conf.d/data.conf']
[2023-03-13T20:19:36.048+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T20:19:36.049+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T20:19:36.050+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T20:19:36.060+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T20:19:36.064+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T200210, start_date=20230313T201935, end_date=20230313T201936
[2023-03-13T20:19:36.083+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 265 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 43547)
[2023-03-13T20:19:36.109+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T20:19:36.130+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
