[2023-03-13T19:58:40.976+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T19:40:38.026613+00:00 [queued]>
[2023-03-13T19:58:40.994+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T19:40:38.026613+00:00 [queued]>
[2023-03-13T19:58:40.995+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:58:40.995+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T19:58:40.995+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:58:41.024+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 19:40:38.026613+00:00
[2023-03-13T19:58:41.027+0000] {standard_task_runner.py:55} INFO - Started process 39848 to run task
[2023-03-13T19:58:41.032+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T19:40:38.026613+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpytecr_iu']
[2023-03-13T19:58:41.034+0000] {standard_task_runner.py:83} INFO - Job 159: Subtask Chargement_des_données_in_ELK
[2023-03-13T19:58:41.113+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T19:40:38.026613+00:00 [running]> on host dev
[2023-03-13T19:58:41.225+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T19:40:38.026613+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T19:40:38.026613+00:00
[2023-03-13T19:58:41.228+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T19:58:41.228+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bin/logstash --path.config /etc/logstash/conf.d/data.conf']
[2023-03-13T19:58:41.240+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T19:58:41.244+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T19:58:41.244+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T19:58:41.259+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T19:58:41.264+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T194038, start_date=20230313T195840, end_date=20230313T195841
[2023-03-13T19:58:41.288+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 159 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 39848)
[2023-03-13T19:58:41.323+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T19:58:41.349+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
